### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by a7medit** [trydis/FIFA-Ultimate-Team-Toolkit#202] opened 2015-12-09 17:18 UTC
I'm always get {"debug":"","string":"","code":"500","reason":""} as a response when trying to get user account

**Comment by bbday** [comment] 2015-12-10 22:54
I don't have this problem, 
Did you get ban?

**Comment by converge** [comment] 2015-12-10 23:43
this is a temporary ban message

**Comment by a7medit** [comment] 2015-12-13 12:51
I did get ban, as i can login normally.

**Comment by a7medit** [comment] 2015-12-13 12:52
tried with different account and got the same response.

**Comment by bbday** [comment] 2015-12-13 14:39
Maybe you have some problem with your code / account, cause nobody have same problem.

**Comment by a7medit** [comment] 2015-12-14 07:43
May you provide a full code sample?, so that i can test it.

**Comment by jvianafec** [comment] 2015-12-14 16:28
An error occurred while sending the request. when trying to log in, someone is having this problem?

**Comment by a7medit** [comment] 2015-12-17 08:46
One more thing, I'm always get 0 as a nucleusId

**Comment by aboo** [comment] 2016-01-05 08:56
I have the same issue. 
I created a new account and the result is the same.
I also tried on UltimateBot. The first account get error message straight away and the second one   (new account) shows the second factor authentication code but fails right after.

**Comment by lorenzh** [comment] 2016-01-05 09:04
i think the two factor authentication was successfull. 
EA added a new Page after the two factor code authentication where you can update the authentication method.

you have to send a POST to cancel the update of authentication method

**Comment by kauefelipe** [comment] 2016-01-06 20:59
Same problem here... 

Someone implemented this "post to cancel"...

```  LoginRequest.cs...
```                var shards = await GetShardsAsync(nucleusId);
```               var userAccounts = await GetUserAccountsAsync(_loginDetails.Platform);

I hope this must be included between this two lines...

**Comment by lorenzh** [comment] 2016-01-07 09:11
i will create a pull request today with the "post to cancel"

**Comment by aboo** [comment] 2016-01-07 10:56
Thanks @lorenzh 
I will try it out and will update here if the problem is solved by that change or not.

**Comment by trydis** [comment] 2016-01-30 23:05
Closing, almost a month without any activity.

**Closed by trydis** 2016-01-30 23:05 UTC
