### ISSUE TITLE
Unable to Login - is this project active?

### ISSUE THREAD

**Issue by lGuzl** [trydis/FIFA-Ultimate-Team-Toolkit#345] opened 2017-07-14 14:39 UTC
Hi guys!!

Im trying to use this tool to dev an app.

when try to use the login function, i get the "unable to login" message. 
I read some issues here, telling to use another loginrequest versions. 
Even with this versions, i have another errors in the httpclient.getasync() method.

Is this project active, and somebody know if this toolkit are ok to use?

**Comment by tringler** [comment] 2017-09-24 17:46
Hello,

the problem is that at the moment nobody knows how the EA ban logic works. At least for me that is the reason why I don't develop on project anymore - This is I think the main reason why the project is a bit on hold. If you can provide me FUT accounts and you have no problems that they will maybe banned I would be able to fix login problems :)

**Comment by tringler** [comment] 2017-09-25 11:46
I will close the issue and handle it with https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/343

**Closed by tringler** 2017-09-25 11:46 UTC
