### ISSUE TITLE
Get captcha

### ISSUE THREAD

**Issue by pashaparenyuk** [trydis/FIFA-Ultimate-Team-Toolkit#344] opened 2017-06-13 12:54 UTC
Cant get captcha:
using toolking 5.0.1
      CaptchaResponse captchaImg = await _client.GetCaptchaAsync();
error 500 code

maybe i use this incorrect: i use getcapthcaasync() into catch block like this
catch(ex)
{
CaptchaResponse captchaImg = await _client.GetCaptchaAsync();
}
pleace help to solve!

And same problem with trigger captcha from today most of bots i know.

**Comment by tringler** [comment] 2017-09-25 11:49
Due to nobody answered on that issue since months, I cannot reproduce the issue and we have a new FUT season I will close the issue for now.

**Closed by tringler** 2017-09-25 11:49 UTC
