### ISSUE TITLE
Unable to login to WebApp

### ISSUE THREAD

**Issue by drawalex** [trydis/FIFA-Ultimate-Team-Toolkit#339] opened 2017-04-09 15:12 UTC
I am trying to run this login class when I do I receive the following exception "Unable to login to WebApp". I am using  FIFA Ultimate Team Toolkit 5.0.0-rc0002 

` class login
    {
        public static FutClient mainFutClient = new FutClient();

        public static async Task User(string username, string password, string securityAnswer, Platform platform)
        {
            var cookieJar = new CookieContainer();
            string fileName = username + @"FUT.cookie." + AppVersion.CompanionApp;
            try
            {
                if (File.Exists(fileName))
                {
                    cookieJar = ReadCookie(fileName);
                    FutClient futClient = new FutClient(cookieJar);

                    var loginDetails = new LoginDetails(username, password, securityAnswer, platform,
                        AppVersion.WebApp);

                    Auth AuthHelper = new Auth();
                    var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

                    mainFutClient = futClient;

                    Console.WriteLine(String.Format("Logged In as {0}.", username));
                }
                else
                {

                    FutClient futClient = new FutClient();

                    var loginDetails = new LoginDetails(username, password, securityAnswer, platform,
                        AppVersion.WebApp);

                    Auth AuthHelper = new Auth();
                    var loginResponse = await futClient.LoginAsync(loginDetails, AuthHelper);

                    Console.WriteLine(loginResponse.SessionId);

                    cookieJar = futClient.RequestFactories.CookieContainer;
                    SaveCookie(fileName, cookieJar);

                    mainFutClient = futClient;

                    Console.WriteLine(String.Format("Logged In as {0}.", username));
                }
            }
            catch (Exception e)
            {
                if (e.Message.Contains("Unable"))
                {
                    Console.WriteLine("The FUT servers are down.");
                }
                else
                {
                    Console.WriteLine(e.Message);
                }

            }

        }

        public partial class Auth : ITwoFactorCodeProvider
        {
            private TaskCompletionSource<string> taskResult = new TaskCompletionSource<string>();

            public Task<string> GetTwoFactorCodeAsync()
            {
                string pin = null;

                Console.WriteLine("Pin Required: ");
                pin = Console.ReadLine();

                taskResult.SetResult(pin);
                return taskResult.Task;
            }
        }

        public static CookieContainer ReadCookie(string file)
        {
            using (Stream stream = File.Open(file, FileMode.Open))
            {
                BinaryFormatter formatter = new BinaryFormatter();
                return (CookieContainer) formatter.Deserialize(stream);
            }
        }

        public static void SaveCookie(string file, CookieContainer cookie)
        {
            using (Stream stream = File.Create(file))
            {
                BinaryFormatter formatter = new BinaryFormatter();
                formatter.Serialize(stream, cookie);
            }
        }
    }`

**Comment by agagrest** [comment] 2017-04-11 09:11
I think it's related to changes made by EA in February. No one manages to fix Toolkit.

**Comment by Bltfast** [comment] 2017-04-11 10:09
actually I have changed LoginRequest.cs and you should find it somewhere in another post.

**Comment by agagrest** [comment] 2017-04-11 13:08
@Bltfast you mean [this](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/333#issuecomment-286837608) ?

**Comment by Bltfast** [comment] 2017-04-11 13:40
nope, [this one](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/333#issuecomment-285310071)...

**Comment by drawalex** [comment] 2017-04-11 18:12
@Bltfast  thanks for your help I have looked at that post and altered the LoginRequest.cs but i get the following exception.
`UltimateTeam.Toolkit.Exceptions.InternalServerException: Code: InternalServerError ---> Newtonsoft.Json.JsonSerializationException: Could not find member 'debug' on object of type 'UserAccounts'. Path 'debug', line 1, position 9.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<DeserializeAsync>d__42`1.MoveNext()
   --- End of inner exception stack trace ---
   at UltimateTeam.Toolkit.Requests.FutRequestBase.MapAndThrowException(Exception exception, FutError futError)
   at UltimateTeam.Toolkit.Requests.FutRequestBase.<DeserializeAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UltimateTeam.Toolkit.Requests.LoginRequest.<GetUserAccountsAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at UltimateTeam.Toolkit.Requests.LoginRequest.<PerformRequestAsync>d__9.MoveNext()`

**Comment by agagrest** [comment] 2017-04-13 08:45
@Bltfast  I don't know why but when I checked these code a few weeks ago it was an exception on LoginRedirect and also now I had this exception but only for the first request. After second try it works. So thanks again! cheers!

**Comment by drawalex** [comment] 2017-04-13 10:32
@agagrest  please can you explain why it works because I am still unable to fix it.

**Comment by Bltfast** [comment] 2017-04-13 10:41
@agagrest I should see your code to better understand what could be the issue... By the way, @drawalex have you removed cached data and did a brand new login access?

**Comment by drawalex** [comment] 2017-04-13 11:10
@Bltfast i have just cleared the cached data and had another run with still no luck

**Comment by shady2k12** [comment] 2017-04-15 16:57
@drawalex I think we are are getting the same error. I managed to isolate the problem to the  `GetUserAccountsAsync(Platform platform)` function in LoginRequest.cs. Specifically
` return await DeserializeAsync<UserAccounts>(accountInfoResponseMessage)` is the line of code that throws this exception. My knowledge is limited but if I can make it work I will let you know.

**Comment by drawalex** [comment] 2017-04-27 12:57
@shady2k12 thanks I'm still unable to get it to work

**Comment by shady2k12** [comment] 2017-04-27 16:50
@drawalex I don't think I changed anything from Bltfast's code. Found the problem was in the Persona.cs file in the Model folder. The class didn't match the HTTP json response (Fiddler). Here are my files [LoginRequest.cs](https://gist.github.com/shady2k12/0a1000d42436b38dfd04d2e6c6c76c27) and [Persona.cs](https://gist.github.com/shady2k12/31ecf8ac6d4b86082270ec45a2e65477)
I started from version 4.0.2. Let me know if it works for you.

**Comment by pashaparenyuk** [comment] 2017-06-06 08:40
Login Failed: Could not find member 'access_token' on object of type 'MobileToken'. Path 'access_token', line 2, position 18.

This ex when i try login with companion app, any ideas what this?

**Comment by drawalex** [comment] 2017-07-09 10:54
@shady2k12 still can't get it to work

**Comment by tringler** [comment] 2017-09-25 11:39
I will close that issue, because it's a duplicate of https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/343

**Closed by tringler** 2017-09-25 11:39 UTC
